apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 80
      targetPort: 5432
      nodePort: 32001
      protocol: TCP