apiVersion: v1
kind: Service
metadata:
  name: kube-foo-service
spec:
  type: NodePort
  selector:
    app: kube-foo-app
  ports:
    - port: 80
      targetPort: 3001
      nodePort: 32001
      protocol: TCP