apiVersion: v1
kind: Service
metadata:
  name: kube-bar-service
spec:
  type: NodePort
  selector:
    app: kube-bar-app
  ports:
    - port: 81
      targetPort: 3002
      nodePort: 32002
      protocol: TCP